### ISSUE TITLE
Issue with multi MX records

### ISSUE THREAD

**Issue by matrixise** [gheesh/ansible-ovh-dns#17]
Hi,

I try to add multiple google MX entries for a domain, and when I check the result, there is only one MX record in the OVH panel.

Sorry, I have not debugged the code, but do you have any idea?

Thank you

```yaml
  - name: Add MX 10 alt3.aspmx.l.google.com.
    ovh_dns:
      state: present
      domain: DOMAIN
      name:
      type: MX
      value: "10 alt3.aspmx.l.google.com."

  - name: Add MX 10 alt4.aspmx.l.google.com.
    ovh_dns:
      state: present
      domain: DOMAIN
      name:
      type: MX
      value: "10 alt4.aspmx.l.google.com."

  - name: Add MX 1 aspmx.l.google.com.
    ovh_dns:
      state: present
      domain: DOMAIN
      name:
      type: MX
      value: "1 aspmx.l.google.com."

  - name: Add 5 alt2.aspmx.l.google.com.
    ovh_dns:
      state: present
      domain: DOMAIN
      name:
      type: MX
      value: "5 alt2.aspmx.l.google.com."

  - name: Add 5 alt1.aspmx.l.google.com.
    ovh_dns:
      state: present
      domain: DOMAIN
      name:
      type: MX
      value: "5 alt1.aspmx.l.google.com."

```

**Comment by lalmeras** [comment]
I suppose only your last record is kept.

You must provide a ``replace: `` with a pattern so that ``ovh_dns`` does not replace all records, but only records with the same priority.

Without ``replace``, ``ovh_dns`` updates the same DOMAIN MX record.

```
  - name: Add MX 1 aspmx.l.google.com.
    ovh_dns:
      state: present
      domain: DOMAIN
      name:
      type: MX
      value: "1 aspmx.l.google.com."
      replace: "1 .*"
  - name: Add 5 alt1.aspmx.l.google.com.
    ovh_dns:
      state: present
      domain: DOMAIN
      name:
      type: MX
      value: "5 alt1.aspmx.l.google.com."
      replace: "5 .*"
```

From my knowledge, you cannot manage multi-value records. I don't know how to handle easily how to set two MX record for each priority.
